VIRTSER_ENABLE = yes

# Not enough interrupts are available, so we have to disable something. I use
# mouse keys (MOUSEKEY_ENABLE) and the volume keys (EXTRAKEY_ENABLE), so I
# didn't want to disable any of those. This is some sort of debugging thing, I
# think, so I disabled it because I don't need it.
CONSOLE_ENABLE = no
